source 'https://github.com/CocoaPods/Specs.git'

target 'VOKBenkode', :exclusive => true do
  pod "VOKBenkode", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "VOKBenkode", :path => "../"
end

target 'Tests-tvOS' do
  platform :tvos, '9.0'
  pod "VOKBenkode", :path => "../"
end
